# Site settings
title: Mirador Electoral
email:
author: 
description:
url:

# Build settings
permalink: :title/
sass:
  sass_dir: css
  
exclude: ['docker-compose.yml','LICENSE','README.md']

defaults:
  - scope:
      path: "assets/img"
