version: "3"

services:
    me_nginx:
        container_name: miradorelectoral_frontend
        build: 
            context: ./
            dockerfile: ./proxy-server/webapp/Dockerfile
        expose:
            - 80
        environment:
            VIRTUAL_HOST: www.miradorelectoral.gt,miradorelectoral.gt
            # LETSENCRYPT_HOST: www.miradorelectoral.gt
            # LETSENCRYPT_EMAIL: javier@guatecambia.org.gt
        volumes:
            - ./proxy-server/webapp/nginx.conf:/etc/nginx/nginx.conf
            - ./proxy-server/webapp/sites/:/etc/nginx/sites-available
networks:
  default:
    external:
      name: nginx-proxy

