version: "3"

services:
    me_nginx_test:
        container_name: miradorelectoral_test
        build: 
            context: ./
            dockerfile: ./proxy-server/webapp/Dockerfile
        expose:
            - 80
        environment:
            VIRTUAL_HOST: prueba.miradorelectoral.gt
        volumes:
            - ./proxy-server/webapp/nginx.conf:/etc/nginx/nginx.conf
            - ./proxy-server/webapp/site-test/:/etc/nginx/sites-available
networks:
  default:
    external:
      name: nginx-proxy

